import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Navbar from "@/componets/Navbar";
import Footer from "@/componets/Footer";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "sonner";

const baiJamjuree = Bai_Jamjuree({
  variable: "--font-bai-jamjuree",
  weight: [ "500"],
});

export const metadata = {
  title: "Hotel Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${baiJamjuree.variable} antialiased bg-slate-50 text-slate-900`}
      >
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />

          {/* ✅ Global Toast */}
          <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
